services:
  app:
    image: ghcr.io/eikjos/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "4321:4321"
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"